version: '3.4'

services:
  # web api service
  logcorner.edusync.speech.command:
    image: logcorner-edusync-speech-command
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Presentation/Dockerfile
    depends_on:
      - logcorner.edusync.speech.command.data
    networks:
      - my_network
 # database service
  logcorner.edusync.speech.command.data:
    image: logcorner-edusync-speech-command-data
    build:
      context: LogCorner.EduSync.Speech/LogCorner.EduSync.Speech.Database/Docker
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: PassW0rd
    networks:
      - my_network    


networks:
  my_network:
    external:
      name: my_network

